import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // We use a manual, not the autogenerated one by Docusaurus in order to have more explicit control on the structure.

  docSidebar: [
    'introduction',
    'use_cases',
    'explorer',

    {
      type: 'category',
      label: 'Protocol',
      items: [
        'protocol/overview',
        'protocol/validators',
        'protocol/consensus',
        'protocol/staking',
        'protocol/rewards',
      ],
    },

    {
      type: 'category',
      label: 'Security',
      items: [
        'security/threat_model',
        'security/audits',
      ],
    },

    {
      type: 'category',
      label: 'Operators',
      items: [
        'operators/overview',
        'operators/configuration',
        'operators/monitoring',
        'operators/troubleshooting',
      ],
    },

    {
      type: 'category',
      label: 'Integration',
      items: [
        'integration/wallets',
        'integration/tx_checkers',
      ],
    },

    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/glossary',
        'reference/faq',
      ],
    },

    'roadmap',
  ],

};

export default sidebars;
